### ISSUE TITLE
Gitflow e Versions

### ISSUE THREAD

**Issue by OtacilioN** [pedrovbeltran/ProjetoGenulic#1]
Já que a ideia é criar o repositório de forma open source e colaborativa, e como foi dito na apresentação, deixar para uso posterior da comunidade, é interessante utilizar-se de um sistema de Gitflow com pelo menos a criação de mais um **branch develop**.

**Comment by pedrovbeltran** [comment]
@OtacilioN Obrigado pelas dicas, como sou novo no GitHub, ainda não conheço todos os recursos que ele tem a oferecer, se pudesse falar mais sobre o GitHub comigo pessoalmente, ficaria muito grato. Obrigado mais uma vez pela colaboração!
